baseURL: 'https://example.org/'
languageCode: 'en-us'
title: 'tortuetec GmbH'
theme: "clarity"
enforceLightMode: true
frontmatter:
    format: yaml
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: imprint
      name: Imprint
      url: /imprint/
      weight: 20