baseURL: 'https://thomasdick-tortuetec.github.io/tortuetec-com/'
languageCode: 'en-us'
title: 'tortuetec GmbH'
module:
  imports:
    - path: github.com/chipzoller/hugo-clarity
enforceLightMode: true
params:
  logo: "tortue-logo.png"
frontmatter:
    format: yaml
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
    - identifier: about
      name: About
      url: "/about/"
      weight: 10
    - identifier: imprint
      name: Imprint
      url: "/imprint/"
      weight: 20